### ISSUE TITLE
Method and Callname overlaps

### ISSUE THREAD

**Issue by TheBay0r** [EnoF/con-rest#22]
When
Method name is to big (e.g. DELETE)

THEN
Method name and call name overlap

![spacingformethodused](https://cloud.githubusercontent.com/assets/8627051/5244997/ef668ef2-7955-11e4-8a65-41923dd3e06f.PNG)

**Comment by EnoF** [comment]
This issue is not reproducible any more, please retest if this is still occurring for you.

**Comment by TheBay0r** [comment]
Looks like it has been resolved with a previous commit
